---
- name: Adding primary group
  group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Adding secondary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Adding secondary groups defined by users
  group:
    name: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ users }}"
    - groups
    - flags:
      skip_missing: True