---
- name: Adding primary group
  group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Adding secondary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"