---

- import_tasks: groups.yml

- name: Adding users
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(users_home ~ '/' ~ item.username ) }}"
    comment: "{{ item.name | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    generate_ssh_key: "{{ item.ssh_key_generate | default(omit) }}"
    group: "{{ omit if item.group is defined and item.group == item.username else (item.group if item.group is defined else (users_group if users_group else omit)) }}"
    groups: "{{ item.groups|join(',') if item.groups is defined else users_groups|join(',')}}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ omit if item.password is not defined else (item.password if item.password == '!' or item.password == '*' else (item.password | password_hash('sha512', 'mysecretsalt'))) }}"
    ssh_key_file: ".ssh/id_{{ item.ssh_key_type | default(users_ssh_key_type) }}"
    ssh_key_passphrase: "{{ item.ssh_key_password | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(users_ssh_key_bits) }}"
    createhome: "{{ item.home_create | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items: "{{ users }}"

- name: Setting user's home permission
  file:
    dest: "{{ item.home | default(users_home ~ '/' ~ item.username) }}"
    owner: "{{ item.home_owner if item.home_owner is defined else item.username }}"
    group: "{{ item.home_group if item.home_group is defined else (item.group if item.group is defined else (users_group if users_group else item.username)) }}"
    mode: "{{ item.home_mode if item.home_mode is defined else users_home_mode }}"
  when: item.home_create is not defined or item.home_create
  with_items: "{{ users }}"

- import_tasks: ssh.yml

- name: Adding user's home files
  copy:
    src: "{{ item.1 }}"
    dest: "{{ item.0.home | default(users_home ~ '/' ~ item.0.username) }}/{{ item.1 | basename }}"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.group if item.0.group is defined else (users_group if users_group else item.0.username) }}"
  with_subelements:
    - "{{ users }}"
    - home_files
    - skip_missing: yes

- name: Adding user's home directories
  file:
    dest: "{{ item.0.home | default(users_home ~ '/' ~ item.0.username) }}/{{ item.1.name | default(item.1) }}"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.group if item.0.group is defined else (users_group if users_group else item.0.username) }}"
    mode: "{{ item.1.mode | default(omit) }}"
    state: directory
  with_subelements:
    - "{{ users }}"
    - home_directories
    - skip_missing: yes

- name: Removing users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ users_remove }}"
