---
- name: Adding user's .ssh directory
  file:
    path: "{{ item.home | default(users_home ~ '/' ~ item.username) }}/.ssh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    state: directory
    mode: '0700'
  when: item.home_create is not defined or item.home_create
  with_items: "{{ users }}"

- name: Adding user's private key
  copy:
    content: "{{ item.ssh_key | default('') }}"
    dest: "{{ item.home | default(users_home ~ '/' ~ item.username) }}/.ssh/id_{{ item.ssh_key_type | default('rsa') }}"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    mode: '0600'
  when: (item.home_create is not defined or item.home_create) and item.ssh_key is defined
  with_items: "{{ users }}"

- name: Adding user's public key
  copy:
    content: "{{ item.ssh_key_public | default('') }}"
    dest: "{{ item.home | default(users_home ~ '/' ~ item.username) }}/.ssh/id_{{ item.ssh_key_type | default('rsa') }}.pub"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    mode: '0600'
  when: (item.home_create is not defined or item.home_create) and item.ssh_key is defined
  with_items: "{{ users }}"

- name: Adding user's ssh private keys
  copy:
    content: "{{ item.1.key }}"
    dest: "{{ item.0.home | default(users_home ~ '/' ~ item.0.username) }}/.ssh/{{ item.1.prefix }}_{{ item.1.key_type | default('rsa') }}"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.group if item.0.group is defined else (users_group if users_group else item.0.username) }}"
  when: item.0.home_create is not defined or item.0.home_create
  with_subelements:
    - "{{ users }}"
    - ssh_private_keys
    - flags:
      skip_missing: True

- name: Adding user's ssh public keys
  copy:
    content: "{{ item.1.key }}"
    dest: "{{ item.0.home | default(users_home ~ '/' ~ item.0.username) }}/.ssh/{{ item.1.prefix }}_{{ item.1.key_type | default('rsa') }}.pub"
    owner: "{{ item.0.username }}"
    group: "{{ item.0.group if item.0.group is defined else (users_group if users_group else item.0.username) }}"
  when: item.0.home_create is not defined or item.0.home_create
  with_subelements:
    - "{{ users }}"
    - ssh_public_keys
    - flags:
      skip_missing: True

- name: Adding user's authorized keys
  authorized_key:
    key: "{{ item.1.key | default(item.1) }}"
    user: "{{ item.0.username }}"
    exclusive: "{{ item.0.authorized_keys_exclusive | default(users_authorized_keys_exclusive) }}"
  when: item.0.home_create is not defined or item.0.home_create
  with_subelements:
    - "{{ users }}"
    - authorized_keys
    - flags:
      skip_missing: True